import { generateMetadata } from "@/components/UI/MetaHeaders";
import Image from "next/image";

export const metadata = generateMetadata({
	title: "About, Config and Vars",
	description:
		"This is currently just to display the config and vars for the app generated by the Electron Installer",
	image: "/main-logo-light-lg.png", // Optional
});

export default function AboutConfigVars() {
	const header = "About, Config and Vars";
	const description = `This is currently just to display the config and vars for the app generated by the Electron Installer`;
	return (
		<div className="mt-6 mx-auto max-w-6xl px-12 md:px-12 lg:px-12 xl:px-6">
			<h1 className="text-3xl font-bold mb-3">{header}</h1>
			<div className="flex flex-col gap-3 ">
				<p>{description}</p>
			</div>
			<div className="flex flex-col gap-3 my-6">
				<ul className="text-sm font-mono">
					<li className="text-blue-300">
						NEXT_PUBLIC_SUPABASE_URL=
						<span className="text-orange-300">
							{process.env.NEXT_PUBLIC_SUPABASE_URL}
						</span>
					</li>
					<li className="text-blue-300">
						NEXT_PUBLIC_SUPABASE_ANON_KEY=
						<span className="text-orange-300">
							{process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!.substring(0, 55)}...
							(Truncated)
						</span>
					</li>
				</ul>
			</div>

			<p>
				This is the logo for the app, uploaded via the Electron Installer - we
				are currently using 2 version dark and light modes
			</p>

			<div className="flex justify-center items-center gap-6">
				<div className="w-1/2 bg-white rounded-lg my-6">
					<Image
						src="/main-logo-dark-lg.png"
						alt="logo"
						className="rounded-lg w-full"
						width={240}
						height={24}
					/>
				</div>
				<div className="w-1/2 bg-zinc-900 rounded-lg">
					<Image
						src="/main-logo-light-lg.png"
						alt="logo"
						className="rounded-lg w-full"
						width={240}
						height={24}
					/>
				</div>
			</div>
		</div>
	);
}
