import { replaceVariables } from "@/lib/email-templates/replaceVariables";
import { sendResendEmail } from "@/lib/resendEmailService";

/**
 * Invoice order - this code was generated via the Admin Email Template Manager tool
 * Please use the Admin manager to create and edit email templates and generate code like this file
 * Date generated: 2025-02-01 10:01:13
 * Generated by Admin User: Joe Gilmore
 */

type EmailInputs = {
	orderID: string;
	products: {
		productName: string;
		productImage: string;
		productPrice: string;
		productQuantity: string;
		productCurrencySymbol: string;
	}[];
	orderTotal: string;
	currencyCode: string;
	currencySymbol: string;
};

// Exported function to send the email
export const sendInvoiceOrder = async (
	toEmailAddress: string,
	inputs: EmailInputs
): Promise<string> => {
	const parsedTemplate = replaceVariables(htmlTemplate, inputs);
	const parsedText = replaceVariables(plainTextTemplate, inputs);
  // console.log(parsedText);
	const emailId = await sendResendEmail({
		to: toEmailAddress,
		subject: "Invoice order",
		body: parsedTemplate,
		text: parsedText,
	});
	return emailId;
};

// The HTML template
const htmlTemplate = `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><!--$-->
<html dir="ltr" lang="en">

  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
    <meta name="x-apple-disable-message-reformatting" />
    <style>
      @media only screen and (max-width: 600px) {
        .row {
          flex-direction: column !important;
          text-align: center;
        }
      }
    </style>
  </head>
  <div style="display:none;overflow:hidden;line-height:1px;opacity:0;max-height:0;max-width:0">Your order has been placed<div> ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿</div>
  </div>

  <body style="background-color:rgb(244,244,245);margin-top:auto;margin-bottom:auto;margin-left:auto;margin-right:auto;font-family:ui-sans-serif, system-ui, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;padding-left:5px;padding-right:5px">
    <table align="center" width="100%" border="0" cellPadding="0" cellSpacing="0" role="presentation" style="border-width:1px;border-style:solid;border-color:rgb(234,234,234);border-radius:0.25rem;margin-top:40px;margin-bottom:40px;margin-left:auto;margin-right:auto;padding:20px;max-width:600px;background-color:rgb(255,255,255)">
      <tbody>
        <tr style="width:100%">
          <td>
            <table align="center" width="100%" border="0" cellPadding="0" cellSpacing="0" role="presentation" style="margin-top:32px">
              <tbody>
                <tr>
                  <td><img alt="Vercel" height="53" src="https://cdn.3dnames.co/tmp/truustit/logo-300.png" style="margin-top:0px;margin-bottom:0px;margin-left:auto;margin-right:auto;display:block;outline:none;border:none;text-decoration:none" width="300" /></td>
                </tr>
              </tbody>
            </table>
            <h1 style="color:rgb(0,0,0);font-size:24px;font-weight:400;text-align:center;padding:0px;margin-top:30px;margin-bottom:30px;margin-left:0px;margin-right:0px">Thank you for your order!</h1>
            <p style="color:rgb(0,0,0);font-size:14px;line-height:24px;margin:16px 0">We appreciate your business. Here are the details of your order:</p>
            <table align="center" width="100%" border="0" cellPadding="0" cellSpacing="0" role="presentation" style="text-align:center;width:100%">
              <tbody>
                <tr>
                  <td>
                    {{#products}}
                    <table align="center" width="100%" border="0" cellPadding="0" cellSpacing="0" role="presentation" style="width:100%;margin-top:0.5rem">
                      <tbody style="width:100%">
                        <tr style="width:100%">
                          <td data-id="__react-email-column" style="width:80px;padding-right:15px"><img alt="{{productName}}" height="60" src="{{productImage}}" style="margin-top:0px;margin-bottom:0px;margin-left:auto;margin-right:auto;object-fit:cover;border-radius:0.375rem;display:block;outline:none;border:none;text-decoration:none" width="80" /></td>
                          <td data-id="__react-email-column" style="text-align:left">
                            <p style="font-size:14px;line-height:24px;margin:16px 0">{{productName}}</p>
                          </td>
                          <td data-id="__react-email-column" style="width:20px;text-align:center">
                            <p style="font-size:14px;line-height:24px;margin:16px 0">x<!-- -->{{productQuantity}}</p>
                          </td>
                          <td data-id="__react-email-column" style="width:100px;text-align:center">
                            <p style="font-size:14px;line-height:24px;margin:16px 0">{{productCurrencySymbol}}<!-- -->{{productPrice}}</p>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                    {{/products}}
                  </td>
                </tr>
              </tbody>
            </table>
            <table align="center" width="100%" border="0" cellPadding="0" cellSpacing="0" role="presentation" style="text-align:center;margin-bottom:20px">
              <tbody>
                <tr>
                  <td>
                    <p style="color:rgb(0,0,0);font-size:1.25rem;line-height:1.75rem;text-align:center;margin:16px 0">Order Total: <b>{{currencySymbol}}<!-- -->{{orderTotal}}<!-- --> {{currencyCode}}</b></p>
                  </td>
                </tr>
              </tbody>
            </table>
            <table align="center" width="100%" border="0" cellPadding="0" cellSpacing="0" role="presentation" style="text-align:center">
              <tbody>
                <tr>
                  <td><a href="https://www.truustit.com/shop/orders/{{orderID}}" class="hover:bg-sky-700" style="background-color:rgb(2,132,199);font-weight:700;color:rgb(255,255,255);border-radius:0.5rem;padding-top:0.75rem;padding-bottom:0.75rem;padding-left:18px;padding-right:18px;text-decoration-line:none" target="_blank">View Your Order</a></td>
                </tr>
              </tbody>
            </table>
            <hr style="border-width:1px;border-style:solid;border-color:rgb(234,234,234);margin-top:26px;margin-bottom:26px;margin-left:0px;margin-right:0px;width:100%;border:none;border-top:1px solid #eaeaea" />
            <p style="color:rgb(102,102,102);font-size:12px;line-height:24px;margin:16px 0">Order ID: <!-- -->{{orderID}}</p>
          </td>
        </tr>
      </tbody>
    </table>
  </body>

</html><!--/$-->`;

// The plain text template
const plainTextTemplate = `THANK YOU FOR YOUR ORDER!

We appreciate your business. Here are the details of your order:

{{#products}}
{{productName}} - {{productCurrencySymbol}}{{productPrice}} - x{{productQuantity}}
{{/products}}

Order Total: {{currencySymbol}}{{orderTotal}} {{currencyCode}}

View Your Order
https://www.truustit.com/shop/orders/{{orderID}}

--------------------------------------------------------------------------------

Order ID: {{orderID}}`;
